### ISSUE TITLE
Compatibility with the latest crazyflie-lib-python 

### ISSUE THREAD

**Issue by Williamwenda** [JGSuw/rospy_crazyflie#1]
Hello, 

I'm interested in using your rospy_crazyflie code for flying Crazyflie. However, I encounter a python incompatibility issue. The latest crazyflie-lib-python seems to work with python3. As a result, when I launch the default.launch file, the code has the trouble to find the cflib as it is installed in python 3 env.

I tried to switch the python interpreter into python 3 (by adding '#! /usr/bin/env python3' on top of each scripts). After that, I got another error of "ImportError: No module named 'crazyflie_client' ". 

I am wondering if you have suggestions to resolve this issue. Any feedback is appreciated.

Thank you in advance!

**Comment by JGSuw** [comment]
Hi William,

I was made aware of this issue recently and I need to put aside some time to sort out what is going wrong with the import sytem, under the current installation instructions. There may be other in compatibilities with Python3 as well. It is my sincere intention to update this repository so that it works for Python3. Admittedly I have put this off for some time, as I am a graduate student, and my present research is largely unrelated to the Smellicopter project.

I will look into this over the weekend, I don't expect it will be very difficult. You can also reach me at my email

jgs6156@uw.edu

and we can correspond privately if you prefer and have more questions about this repository.

**Comment by Williamwenda** [comment]
Hi Joseph,

Thank you so much for the quick reply. Our lab has a ground station code to fly Crayzflies. However, the communication code is a bit old and not compatible with the new crazyflie-firmware. Therefore, I am searching online to see if there are projects based on the official crazyflie-python-API. Your project is pretty helpful for a python-based CF ground station.

It would be great if you can briefly check the python 3 environment issue during the weekends. I will also try to fix the problems myself. We can have further discussions via email. (my email is: wenda.zhao@mail.utoronto.ca)

I am very appreciated with your help!

Thanks,

Wenda

**Comment by JGSuw** [comment]
Wenda,

Probably the simplest solution to this problem is for you to install [crazyflie-lib-python](https://github.com/bitcraze/crazyflie-lib-python/tree/0.13) into your python2 environment, instead of your python3 environment.

Fixing this is as simple as invoking the right `pip` program when running `pip install -e .` in the crazyflie-lib-python directory.

For example, if your python 2 interpreter is `python2` then you can run `python2 -m pip install -e .` 

Can you try this and let me know if that fixes the import problem?

As for _actual_ python 3 support, that is going to be a more complicated endeavor. For now, I will try to build this repository on a ROS Noetic distribution, which supports Python 3, and hopefully this does not break anything.

**Comment by Williamwenda** [comment]
Hi Joseph,

Thank you very much for looking into this problem.

I tested to install the crazyflie-lib-python into the python2 environment. However, I got the import error of 'No module named 'Queue' and it is because the 'queue' module is lower case in python3. (check this [link](https://stackoverflow.com/questions/33432426/importerror-no-module-named-queue))

I think the latest crazyflie-lib-python is written in python 3 and there may exist many small import errors like the 'queue' module. 

Building this repository on ROS Noetic would probably be the best solution as it supports Python 3 exclusively. I will try it out sometime next week and provide the feedback to you. 

I really appreciated your help! 
Thanks.

Wenda

**Comment by JGSuw** [comment]
Hi Wenda,

I tried to follow up with you since you were having this issue. I have since updated the repository to work with Python 3 on Noetic, this functionality is on the python3-migration branch. For now I will close this issue, please feel free to reopen if your problem persists and you are still interested in using the repository.
